### ISSUE TITLE
How to Run?

### ISSUE THREAD

**Issue by ops-jaeha** [limkhashing/Face-Matching#15]
I opened the server and put one image and one video in the "/" url and ran it.
However, the following error occurs.
> [2022-10-18 16:03:41,016] ERROR in app: Exception on /api/upload [POST]
> Traceback (most recent call last):
>   File "/home/user/anaconda3/envs/face-match/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/user/anaconda3/envs/face-match/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/user/anaconda3/envs/face-match/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/user/anaconda3/envs/face-match/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/home/user/programing/dob/face-similarity/Face-Matching/app.py", line 170, in upload_image_video
>     return compare_face(known_filename_path,
>   File "/home/user/programing/dob/face-similarity/Face-Matching/src/face_processing.py", line 66, in compare_face
>     extract_frames_from_video(video_path, request_frames_folder_path)
>   File "/home/user/programing/dob/face-similarity/Face-Matching/src/orientation_processing.py", line 51, in extract_frames_from_video
>     rotate_code = check_rotation(video_path)
>   File "/home/user/programing/dob/face-similarity/Face-Matching/src/orientation_processing.py", line 17, in check_rotation
>     meta_dict = ffmpeg.probe(path_video_file)
>   File "/home/user/anaconda3/envs/face-match/lib/python3.8/site-packages/ffmpeg/_probe.py", line 20, in probe
>     p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "/home/user/anaconda3/envs/face-match/lib/python3.8/subprocess.py", line 858, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/home/user/anaconda3/envs/face-match/lib/python3.8/subprocess.py", line 1704, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

How to run this api ?

**Comment by cv-jaeha** [comment]
Solution
$ sudo apt update
$ sudo apt install ffmpeg

**Comment by cv-jaeha** [comment]
This time this error
> pytesseract.pytesseract.TesseractNotFoundError: /app/.apt/usr/bin/tesseract is not installed or it's not in your PATH. See README file for more information.

**Comment by limkhashing** [comment]
@cv-jaeha Hello sorry missed your issue. For the error TesseractNotFoundError, you need to download [Tesseract OCR binary](https://tesseract-ocr.github.io/tessdoc/Downloads.html). 

After that, please set the path to your Tesseract OCR binary, so that the code able to find the binary and execute OCR

**Comment by limkhashing** [comment]
I'm assume you are able to fix the error. WIll be closing this issue for now. Any problem please create new issue again
